version: "3"

services:
  service-nodes-and-pools:
    volumes:
      - ./service/nodes-and-pools:/go
    command: tail -f /dev/null

  # service-daemon-cache:
  #   volumes:
  #     - ./service/daemon-cache:/go
  #   command: tail -f /dev/null

  web-backend:
    volumes:
      - ./web/backend:/home/node
    command: tail -f /dev/null

  web-frontend:
    volumes:
      - ./web/frontend:/home/node
    command: tail -f /dev/null
